import { Activity, Ambulance, Brush, Car, ChefHat, Drill, HeartPulse, Home, LayoutGrid, PaintBucket, Shield, Siren, Square, Zap, type LucideIcon } from 'lucide-react';
import { ServiceListingDetail } from './types';

export const SERVICE_LISTING_DETAILS: ServiceListingDetail[] = [
  {
    id: 'maid',
    titleEn: 'Maid Services',
    titleBn: 'গৃহকর্মী সেবা',
    image: 'https://images.unsplash.com/photo-1758272421751-963195322eaa?w=1200&q=80',
    shortDescription: 'Professional household support from regular cleaning to deep care routines for modern homes.',
    servicesOffered: ['Regular cleaning', 'Deep cleaning', 'Kitchen sanitization', 'Bathroom cleaning', 'Laundry support', 'Elderly support'],
    highlights: ['Daily support', 'Verified profiles', 'Flexible schedule', 'Female/male provider options'],
  },
  {
    id: 'driver',
    titleEn: 'Driver Services',
    titleBn: 'ড্রাইভার সেবা',
    image: 'https://images.unsplash.com/photo-1764328165995-0624c280a6d2?w=1200&q=80',
    shortDescription: 'Safe and punctual drivers for office commute, airport transfer, and long-hour city movement.',
    servicesOffered: ['Hourly driver hire', 'Airport transfer', 'Daily office commute', 'Corporate trips', 'Weekend trips', 'Long distance rides'],
    highlights: ['Background checked', 'City-route experts', 'On-time commitment', 'Local + expert tiers'],
  },
  {
    id: 'chef',
    titleEn: 'Chef Services',
    titleBn: 'রাঁধুনি সেবা',
    image: 'https://images.unsplash.com/photo-1775871104670-821a65a04c7a?w=1200&q=80',
    shortDescription: 'Home and event chefs for curated meals, regional cuisine, and family-ready meal prep plans.',
    servicesOffered: ['Daily home cooking', 'Event catering', 'Traditional cuisine', 'Continental menu', 'Meal prep', 'Dessert prep'],
    highlights: ['Taste profile matching', 'Hygiene-focused', 'Custom portions', 'Ingredient coordination'],
  },
  {
    id: 'plumber',
    titleEn: 'Plumber Services',
    titleBn: 'প্লাম্বার সেবা',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&q=80',
    shortDescription: 'Fast response plumbing for leak control, fixture replacement, and bathroom pipeline maintenance.',
    servicesOffered: ['Leak repair', 'Pipe replacement', 'Tap/faucet fitting', 'Drain cleaning', 'Water line check', 'Bathroom fittings'],
    highlights: ['Emergency support', 'Parts recommendation', 'Neat finishing', 'Post-job checklist'],
  },
  {
    id: 'electrician',
    titleEn: 'Electrician Services',
    titleBn: 'ইলেকট্রিশিয়ান সেবা',
    image: 'https://images.unsplash.com/photo-1653669486771-8ee1ea4d7af8?w=1200&q=80',
    shortDescription: 'Certified electrical support for diagnostics, installations, and safety-first home rewiring tasks.',
    servicesOffered: ['Fault diagnostics', 'Switch/socket repair', 'Wiring and rewiring', 'Lighting setup', 'AC line setup', 'DB panel check'],
    highlights: ['Safety protocols', 'Voltage tools', 'Transparent estimate', 'Follow-up checks'],
  },
  {
    id: 'nursing',
    titleEn: 'Nursing Services',
    titleBn: 'নার্সিং সেবা',
    image: 'https://images.unsplash.com/photo-1765896387387-0538bc9f997e?w=1200&q=80',
    shortDescription: 'Compassionate home nursing care for recovery, elderly support, and post-procedure assistance.',
    servicesOffered: ['Post-op care', 'Elderly support', 'Medication management', 'Vital monitoring', 'Wound dressing', 'Bedridden support'],
    highlights: ['Registered staff', 'Care protocols', 'Family updates', 'Shift-based options'],
  },
  {
    id: 'physiotherapy',
    titleEn: 'Physio Services',
    titleBn: 'ফিজিওথেরাপি সেবা',
    image: 'https://images.unsplash.com/photo-1545463913-5083aa7359a6?w=1200&q=80',
    shortDescription: 'Clinical physiotherapy sessions at home for mobility recovery, pain relief, and therapy tracking.',
    servicesOffered: ['Pain therapy sessions', 'Mobility rehab', 'Stroke recovery support', 'Sports injury rehab', 'Joint care plans', 'Posture correction'],
    highlights: ['Home sessions', 'Progress tracking', 'Doctor-coordinated plans', 'Personalized exercises'],
  },
  {
    id: 'ambulance',
    titleEn: 'Ambulance Services',
    titleBn: 'অ্যাম্বুলেন্স সেবা',
    image: 'https://images.unsplash.com/photo-1655084131262-73cbdc46522b?w=1200&q=80',
    shortDescription: '24/7 ambulance support for emergency transfer, managed transport, and response coordination.',
    servicesOffered: ['Emergency transport', 'ICU ambulance', 'Inter-hospital transfer', 'Bed-to-bed support', 'Night response', 'Medical escort'],
    highlights: ['Rapid dispatch', 'Response tracking', 'Medical team support', 'Critical route coordination'],
  },
  {
    id: 'carpenter',
    titleEn: 'Carpenter Services',
    titleBn: 'কার্পেন্টার সেবা',
    image: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=1200&q=80',
    shortDescription: 'Custom woodwork and furniture fixes for home improvements with precision finishing.',
    servicesOffered: ['Cabinet repair', 'Door installation', 'Custom shelving', 'Wardrobe fixes', 'Furniture assembly', 'Polish and finish'],
    highlights: ['Measurement first', 'Material guidance', 'Finish quality', 'On-site custom work'],
  },
  {
    id: 'plasterer',
    titleEn: 'Plasterer Services',
    titleBn: 'প্লাস্টারার সেবা',
    image: 'https://images.unsplash.com/photo-1601058268499-e52658b8bb88?w=1200&q=80',
    shortDescription: 'Wall and ceiling plaster finishing for smooth surfaces before premium paint or décor work.',
    servicesOffered: ['Wall crack repair', 'Ceiling plaster', 'Surface leveling', 'Edge finishing', 'Corner patchwork', 'Paint prep smoothening'],
    highlights: ['Dust-managed process', 'Even texture', 'Fast curing prep', 'Renovation-friendly'],
  },
  {
    id: 'tiler',
    titleEn: 'Tiler Services',
    titleBn: 'টাইল বিশেষজ্ঞ সেবা',
    image: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=1200&q=80',
    shortDescription: 'Specialist tile installation and replacement with consistent alignment and durable grout finish.',
    servicesOffered: ['Floor tiling', 'Wall tiling', 'Tile replacement', 'Grout correction', 'Bathroom tile setup', 'Kitchen backsplash'],
    highlights: ['Alignment precision', 'Level checks', 'Waterproof prep', 'Durable finishing'],
  },
  {
    id: 'painter',
    titleEn: 'Painters & Decorators',
    titleBn: 'পেইন্টার ও ডেকোরেটর সেবা',
    image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=1200&q=80',
    shortDescription: 'Interior and exterior finishing with color consultation, texture options, and clean execution.',
    servicesOffered: ['Interior painting', 'Exterior painting', 'Texture coat', 'Putty & primer', 'Color consultation', 'Touch-up work'],
    highlights: ['Color accuracy', 'Neat masking', 'Fast turnaround', 'Decorative options'],
  },
  {
    id: 'bricklayer',
    titleEn: 'Brick Layer Services',
    titleBn: 'ইট মিস্ত্রি সেবা',
    image: 'https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?w=1200&q=80',
    shortDescription: 'Skilled masonry for small structures, wall repairs, and partition layout work.',
    servicesOffered: ['Boundary wall work', 'Partition wall setup', 'Brick repair', 'Masonry touchup', 'Small structure build', 'Foundation patching'],
    highlights: ['Site estimation', 'Material ratio control', 'Strong bonding', 'Structural care'],
  },
  {
    id: 'flooring',
    titleEn: 'Flooring Specialists/Agency',
    titleBn: 'ফ্লোরিং বিশেষজ্ঞ সেবা',
    image: 'https://images.unsplash.com/photo-1616627452094-a95cc4e2d6f7?w=1200&q=80',
    shortDescription: 'Flooring experts for tile, vinyl, and wood solutions with long-lasting installation quality.',
    servicesOffered: ['Tile flooring', 'Vinyl flooring', 'Wood finish floor', 'Floor leveling', 'Skirting setup', 'Polishing and protection'],
    highlights: ['Material + labor split', 'Finish warranty', 'Installation checklist', 'Post-install care guide'],
  },
];

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  all: LayoutGrid,
  maid: Home,
  driver: Car,
  chef: ChefHat,
  plumber: Drill,
  electrician: Zap,
  nursing: HeartPulse,
  physiotherapy: Activity,
  ambulance: Ambulance,
  carpenter: Shield,
  plasterer: PaintBucket,
  tiler: Square,
  painter: Brush,
  bricklayer: Siren,
  flooring: Square,
};

export const SERVICE_FAQS = [
  {
    q: 'Are all listed providers verified before booking?',
    a: 'Yes. Providers pass onboarding checks and category-specific requirements before they are visible for booking.',
  },
  {
    q: 'Can I compare price and quality before selecting?',
    a: 'Yes. Each service card shows provider volume, expert ratio, rating, and base pricing before you proceed.',
  },
  {
    q: 'Can I book urgent services for today?',
    a: 'For available categories and zones, same-day providers are prioritized and shown first in listing results.',
  },
  {
    q: 'Is there support for claim and dispute handling?',
    a: 'Yes. You can submit claim evidence in-app, and the system routes the case into response and mediation workflow.',
  },
];
